version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 15
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'maven'
    directory: '/src/main/resources/generator/dependencies/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'gradle'
    directory: '/src/main/resources/generator/dependencies/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/.github/actions/setup'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/common'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
    ignore:
      - dependency-name: 'node'
        versions: ['15.x', '17.x', '19.x', '21.x']
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/vue'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/react'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/angular'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
    groups:
      angular:
        patterns:
          - '@angular*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'

  - package-ecosystem: 'docker'
    directory: '/src/main/resources/generator/dependencies'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
