version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 15
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'maven'
    directory: '/src/main/resources/generator/dependencies/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/.github/actions/setup'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/common'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/vue'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/react'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/svelte'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
  - package-ecosystem: 'npm'
    directory: '/src/main/resources/generator/dependencies/angular'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    labels:
      - 'area: dependencies'
