name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  #--------------------------------------------------
  # Build and Tests the project on Windows
  #--------------------------------------------------
  tests-windows:
    name: tests-windows
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Test: run backend tests'
        run: |
          ./mvnw clean verify
  #--------------------------------------------------
  # Build and Tests the project on Linux
  #--------------------------------------------------
  tests-linux:
    name: tests-linux
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Check: prettier'
        run: npm run prettier:check
      - name: 'Test: run backend tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      - name: 'Analysis: SonarCloud'
        if: github.repository == 'jhipster/jhipster-lite' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw initialize sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=jhipster_jhipster-lite -Dsonar.organization=jhipster
      - name: 'Artifact: upload JaCoCo report'
        uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: '${{ github.workspace }}/target/jacoco/jacoco.xml'
          retention-days: 1
      - name: 'Artifact: upload JAR'
        uses: actions/upload-artifact@v2
        with:
          name: jhlite-jar
          path: '${{ github.workspace }}/target/*.jar'
          retention-days: 1
  #--------------------------------------------------
  # Tests generated projects
  #--------------------------------------------------
  generation:
    needs: [tests-linux]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - full-default
          - tomcat-mysql-ehcachexml
          - undertow-simplecache
          - tomcat-configserver
          - undertow-consul
          - tomcat-mongodb
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Artifact: download JAR'
        uses: actions/download-artifact@v2
        with:
          name: jhlite-jar
          path: ./tests-ci/
      - name: 'Generation: generate ${{ matrix.app }}'
        working-directory: ./tests-ci/
        run: |
          ./start.sh
          ./generate.sh ${{ matrix.app }}
          ./stop.sh
      - name: 'Test: list ${{ matrix.app }}'
        id: cache_md5sum
        run: |
          ls -al /tmp/jhlite/${{ matrix.app }}
          MD5SUM_POM_XML=$(md5sum /tmp/jhlite/${{ matrix.app }}/pom.xml | cut -d ' ' -f 1)
          echo $MD5SUM_POM_XML
          echo ::set-output name=md5sum_pom_xml::${MD5SUM_POM_XML}
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.app }}-${{ steps.cache_md5sum.outputs.md5sum_pom_xml }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Test: verify ${{ matrix.app }}'
        working-directory: /tmp/jhlite/${{ matrix.app }}/
        run: |
          chmod +x mvnw
          ./mvnw clean verify
  #--------------------------------------------------
  # Send analysis to Codecov
  #--------------------------------------------------
  codecov:
    needs: generation
    name: codecov
    if: github.repository == 'jhipster/jhipster-lite'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Artifact: download JaCoCo report'
        uses: actions/download-artifact@v2
        with:
          name: jacoco
      - name: 'Codecov: sending analysis...'
        uses: codecov/codecov-action@v2
        with:
          files: jacoco.xml
          fail_ci_if_error: true
          verbose: true
